export const EMOJI_SHORTCODES: Readonly<Record<string, string>> = {
  '+1': '👍',
  '-1': '👎',
  blush: '😊',
  bulb: '💡',
  checkered_flag: '🏁',
  clap: '👏',
  eyes: '👀',
  fire: '🔥',
  heart: '❤️',
  heavy_check_mark: '✔️',
  information_source: 'ℹ️',
  joy: '😂',
  memo: '📝',
  rocket: '🚀',
  smile: '😄',
  sparkles: '✨',
  star: '⭐',
  tada: '🎉',
  thinking: '🤔',
  warning: '⚠️',
  wave: '👋',
  white_check_mark: '✅',
  x: '❌',
  zap: '⚡',
};
